I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00keymap.rpy", line 421, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 421, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 421, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 440, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
AttributeError: 'NoneType' object has no attribute 'stores'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\bootstrap.py", line 314, in bootstrap
    renpy.main.main()
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\main.py", line 431, in main
    if renpy.parser.report_parse_errors():
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\parser.py", line 2926, in report_parse_errors
    renpy.display.error.report_parse_errors(full_text, error_fn)
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\display\error.py", line 187, in report_parse_errors
    error_fn=error_fn,
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\game.py", line 281, in invoke_in_new_context
    return callable(*args, **kwargs)
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\display\error.py", line 45, in call_exception_screen
    return renpy.ui.interact(mouse="screen", type="screen", suppress_overlay=True, suppress_underlay=True)
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\ui.py", line 295, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\display\core.py", line 2699, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\display\core.py", line 3163, in interact_core
    renpy.exports.reload_script()
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\exports.py", line 1762, in reload_script
    renpy.game.call_in_new_context("_save_reload_game")
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\game.py", line 332, in call_in_new_context
    return renpy.execution.run_context(False)
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\execution.py", line 892, in run_context
    context.run()
  File "renpy/common/00keymap.rpy", line 421, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 421, in script
    python hide:
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\ast.py", line 912, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\python.py", line 2004, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00keymap.rpy", line 421, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 440, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\loadsave.py", line 398, in save
    roots = renpy.game.log.freeze(None)
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\python.py", line 1901, in freeze
    self.complete(False)
  File "E:\Documents\Games\renpy-7.3.2-sdk\renpy\python.py", line 1511, in complete
    self.current.stores[name], self.current.delta_ebc[name] = sd.get_changes(begin)
AttributeError: 'NoneType' object has no attribute 'stores'

Windows-7-6.1.7601-SP1
Ren'Py 7.3.2.320
 
Fri Sep 20 22:26:15 2019
